### ISSUE TITLE
composer.lock中包含失效的url

### ISSUE THREAD

**Issue by sezethon** [luvvien/laravel-blog#2]
建议作者把composer.lock删了, 因为里面的指向https://dl.laravel-china.org的url地址, 现在都已经失效了.

**Comment by luvvien** [comment]
> 建议作者把composer.lock删了, 因为里面的指向[https://dl.laravel-china.org的url地址](https://dl.laravel-china.org%E7%9A%84url%E5%9C%B0%E5%9D%80), 现在都已经失效了.

感谢建议，已删
